package interfaceGraphique;


import java.awt.Color;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import lancerRayon.*;

public class LumiereAmbiante extends javax.swing.JFrame {

    private BufferedImage imageApercu;
    private Scene scene;

    /** Creates new form LumiereAmbiante */
    public LumiereAmbiante(Scene scene_) {
        scene=scene_;
        initComponents();
        imageApercu=new BufferedImage(30,30,1);
        for(int i=0;i<30;i++){
            for(int j=0;j<30;j++){
                imageApercu.setRGB(i, j,jSliderB.getValue()+256*jSliderV.getValue()+256*256*jSliderR.getValue());
            }
        }
        ImageIcon iconApercu=new ImageIcon(imageApercu);
        LabelApercu.setIcon(iconApercu);
        jSliderB.addChangeListener(new ActionChangementB());
        jSliderV.addChangeListener(new ActionChangementV());
        jSliderR.addChangeListener(new ActionChangementR());
    }

    public LumiereAmbiante(Scene scene_,Color couleur) {
        scene=scene_;
        initComponents();
        jSliderR.setValue(couleur.getRed());
        jSliderV.setValue(couleur.getGreen());
        jSliderB.setValue(couleur.getBlue());
        imageApercu=new BufferedImage(30,30,1);
        for(int i=0;i<30;i++){
            for(int j=0;j<30;j++){
                imageApercu.setRGB(i, j,jSliderB.getValue()+256*jSliderV.getValue()+256*256*jSliderR.getValue());
            }
        }
        ImageIcon iconApercu=new ImageIcon(imageApercu);
        LabelApercu.setIcon(iconApercu);
        jSliderB.addChangeListener(new ActionChangementB());
        jSliderV.addChangeListener(new ActionChangementV());
        jSliderR.addChangeListener(new ActionChangementR());
    }

    class ActionChangementB implements ChangeListener{
        public void stateChanged(ChangeEvent e) {
            BufferedImage imageApercu=new BufferedImage(30,30,1);
            for(int i=0;i<30;i++){
                for(int j=0;j<30;j++){
                    imageApercu.setRGB(i, j,jSliderB.getValue()+256*jSliderV.getValue()+256*256*jSliderR.getValue());
                }
            }
            ImageIcon iconApercu=new ImageIcon(imageApercu);
            LabelApercu.setIcon(iconApercu);
        }
	}

    class ActionChangementV implements ChangeListener{
        public void stateChanged(ChangeEvent e) {
            BufferedImage imageApercu=new BufferedImage(30,30,1);
            for(int i=0;i<30;i++){
                for(int j=0;j<30;j++){
                    imageApercu.setRGB(i, j,jSliderB.getValue()+256*jSliderV.getValue()+256*256*jSliderR.getValue());
                }
            }
            ImageIcon iconApercu=new ImageIcon(imageApercu);
            LabelApercu.setIcon(iconApercu);
        }
	}

    class ActionChangementR implements ChangeListener{
        public void stateChanged(ChangeEvent e) {
            BufferedImage imageApercu=new BufferedImage(30,30,1);
            for(int i=0;i<30;i++){
                for(int j=0;j<30;j++){
                    imageApercu.setRGB(i, j,jSliderB.getValue()+256*jSliderV.getValue()+256*256*jSliderR.getValue());
                }
            }
            ImageIcon iconApercu=new ImageIcon(imageApercu);
            LabelApercu.setIcon(iconApercu);
        }
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BoutonValider = new javax.swing.JButton();
        BoutonAnnuler = new javax.swing.JButton();
        jSliderR = new javax.swing.JSlider();
        jSliderB = new javax.swing.JSlider();
        jSliderV = new javax.swing.JSlider();
        ValeurR = new javax.swing.JLabel();
        ValeurG = new javax.swing.JLabel();
        ValeurB = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LabelApercu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lumiere ambiante");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lumiere Ambiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 0, 13), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setText("Intensite : ");

        jLabel2.setText("R :");

        jLabel3.setText("V :");

        jLabel4.setText("B :");

        BoutonValider.setText("Valider");
        BoutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonValiderActionPerformed(evt);
            }
        });

        BoutonAnnuler.setText("Annuler");
        BoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAnnulerActionPerformed(evt);
            }
        });

        jSliderR.setMaximum(255);
        jSliderR.setPaintLabels(true);
        jSliderR.setPaintTicks(true);
        jSliderR.setValue(0);

        jSliderB.setMaximum(255);
        jSliderB.setPaintLabels(true);
        jSliderB.setPaintTicks(true);
        jSliderB.setValue(0);

        jSliderV.setMaximum(255);
        jSliderV.setPaintLabels(true);
        jSliderV.setPaintTicks(true);
        jSliderV.setValue(0);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderR, org.jdesktop.beansbinding.ELProperty.create("${value}"), ValeurR, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderV, org.jdesktop.beansbinding.ELProperty.create("${value}"), ValeurG, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderB, org.jdesktop.beansbinding.ELProperty.create("${value}"), ValeurB, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel6.setText("Aperçu :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValeurR))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSliderV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValeurG))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSliderB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ValeurB))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(238, 238, 238)
                                        .addComponent(jLabel6))
                                    .addComponent(BoutonValider, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BoutonAnnuler)
                                    .addComponent(LabelApercu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ValeurR)
                                .addComponent(jLabel6)))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValeurG)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(LabelApercu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jSliderB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValeurB))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BoutonValider)
                            .addComponent(BoutonAnnuler))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonValiderActionPerformed
       scene.setLumiereAmbiante(new Color(jSliderR.getValue(),jSliderV.getValue(),jSliderB.getValue()));
       this.dispose();
}//GEN-LAST:event_BoutonValiderActionPerformed

    private void BoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAnnulerActionPerformed
       this.dispose();
    }//GEN-LAST:event_BoutonAnnulerActionPerformed

    /**
    * @param args the command line arguments
    */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LumiereAmbiante().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonValider;
    private javax.swing.JLabel LabelApercu;
    private javax.swing.JLabel ValeurB;
    private javax.swing.JLabel ValeurG;
    private javax.swing.JLabel ValeurR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSliderB;
    private javax.swing.JSlider jSliderR;
    private javax.swing.JSlider jSliderV;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
